# Generated by Django 3.2.6 on 2022-01-09 23:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد اقدام')),
                ('actionDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح اقدام')),
                ('actionIsActive', models.BooleanField(blank=True, default=True, verbose_name='فعال')),
            ],
            options={
                'db_table': 'actioncode',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetTypes', models.IntegerField(blank=True, choices=[(1, 'مکان'), (2, 'ماشین  آلات'), (3, 'ابزارآلات')], null=True, verbose_name='نوع دارایی')),
                ('assetName', models.CharField(max_length=100, verbose_name='مشخصات')),
                ('assetDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('assetCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد')),
                ('assetAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('assetCity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('assetState', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('assetZipcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پستی')),
                ('assetCountry', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('assetAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب')),
                ('assetChargeDepartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان مسوول')),
                ('assetNotes', models.CharField(blank=True, max_length=100, null=True, verbose_name='یادداشت')),
                ('assetBarcode', models.IntegerField(blank=True, null=True, verbose_name='بارکد')),
                ('assetHasPartOf', models.BooleanField(default=False)),
                ('assetAisel', models.IntegerField(blank=True, null=True, verbose_name='راهرو')),
                ('assetRow', models.IntegerField(blank=True, null=True, verbose_name='ردیف')),
                ('assetBin', models.IntegerField(blank=True, null=True, verbose_name='Bin')),
                ('assetManufacture', models.CharField(blank=True, max_length=50, null=True, verbose_name='سازنده')),
                ('assetModel', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('assetSerialNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سریال')),
                ('assetStatus', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('assetIsStock', models.BooleanField(default=False, verbose_name='انبار')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('priority', models.IntegerField(null=True, verbose_name='اولویت')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetcategory', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'assetcategory',
            },
        ),
        migrations.CreateModel(
            name='AssetMeterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetMeterTemplateDesc', models.CharField(blank=True, max_length=50, null=True, verbose_name='شرح')),
                ('assetMeterTemplateAsset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='نام دارایی')),
            ],
            options={
                'db_table': 'Assetmetertemplate',
            },
        ),
        migrations.CreateModel(
            name='BOMGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOMGroupName', models.CharField(max_length=50, unique=True, verbose_name='نام گروه BOM')),
            ],
            options={
                'db_table': 'bomgroup',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('primaryContact', models.CharField(blank=True, max_length=100, null=True, verbose_name='مشخصات تماس')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن 2')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='فکس')),
                ('webSite', models.CharField(blank=True, max_length=50, null=True, verbose_name='سایت')),
                ('primaryEmail', models.CharField(blank=True, max_length=50, null=True, verbose_name='ایمیل اصلی')),
                ('secondyEmail', models.CharField(blank=True, max_length=50, null=True, verbose_name='ایمیل 2')),
                ('primaryCurrency', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد پول')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='یادداشت')),
                ('isSupplier', models.BooleanField(default=False, verbose_name='تامین کننده')),
                ('insManufacturer', models.BooleanField(default=False, verbose_name='سازننده')),
                ('isServiceProvider', models.BooleanField(default=False, verbose_name='سرویس پروایدر')),
                ('isOwner', models.BooleanField(default=False, verbose_name='مالک')),
                ('isCustomer', models.BooleanField(default=False, verbose_name='مشتری')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پستی')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='CauseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causeCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد علت')),
                ('causeDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح علت')),
                ('causeIsActive', models.BooleanField(blank=True, default=True, verbose_name='فعال')),
            ],
            options={
                'db_table': 'causecode',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رویداد')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رویداد')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('color', models.CharField(default='#FF0000', max_length=10, verbose_name='رنگ')),
            ],
            options={
                'db_table': 'maintenancetype',
            },
        ),
        migrations.CreateModel(
            name='MeterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد')),
                ('meterDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='َشرح')),
                ('meterAbbr', models.CharField(blank=True, max_length=5, null=True, verbose_name='اختصار')),
            ],
            options={
                'db_table': 'metercode',
            },
        ),
        migrations.CreateModel(
            name='MiniWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'miniworkorder',
            },
        ),
        migrations.CreateModel(
            name='MiscCostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscCostCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد')),
                ('miscCostDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='َشرح')),
            ],
            options={
                'db_table': 'misccostcode',
            },
        ),
        migrations.CreateModel(
            name='OfflineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رویداد')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رویداد')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح')),
            ],
            options={
                'db_table': 'offlinestatus',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=100, verbose_name='مشخصات')),
                ('partDescription', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('partCode', models.CharField(max_length=50, verbose_name='کد')),
                ('partMake', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساخته شده توسط')),
                ('partModel', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('partLastPrice', models.FloatField(blank=True, default=0, null=True, verbose_name='آخرین قیمت')),
                ('partAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب')),
                ('partChargeDepartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان مسوول')),
                ('partNotes', models.CharField(blank=True, max_length=100, null=True, verbose_name='یادداشت')),
                ('partBarcode', models.IntegerField(blank=True, null=True, verbose_name='بارکد')),
                ('partInventoryCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد قفسه')),
            ],
            options={
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='PertCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد پرت')),
                ('pertDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح')),
            ],
            options={
                'db_table': 'pertcode',
            },
        ),
        migrations.CreateModel(
            name='ProblemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد مشکل')),
                ('problemDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح مشکل')),
                ('problemIsActive', models.BooleanField(blank=True, default=True, verbose_name='فعال')),
            ],
            options={
                'db_table': 'problemcode',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100, verbose_name='نام')),
                ('projectDescription', models.TextField(verbose_name='شرح')),
                ('ProjectStartDate', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ شروع پروژه')),
                ('ProjectEndDate', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ پایان پروژه')),
                ('ProjectActualStartDate', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ شروع واقعی پروژه')),
                ('ProjectActualEndDate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ واقعی اتمام پروژه')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام گزارش')),
                ('reportCategory', models.IntegerField(blank=True, choices=[(1, 'دستور کار فعال'), (2, 'دستور کار غیر فعال'), (3, 'کنترل انبار'), (4, 'دارایی'), (5, 'کاربران'), (6, 'اندازه گیری کسب و کار'), (7, 'شخصی سازی شده'), (8, 'پیش بینی'), (9, 'نگهداری زمانبندی شده')], null=True, verbose_name='نوع گزارش')),
                ('reportClassName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کلاس')),
                ('reportDetails', models.TextField(blank=True, null=True, verbose_name='شرح')),
                ('reportTemplate', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام قالب')),
                ('reportFav', models.BooleanField(default=True, verbose_name='گزارش مورد علاقه')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyOnHand', models.IntegerField(blank=True, null=True, verbose_name='موجودی')),
                ('minQty', models.IntegerField(blank=True, null=True, verbose_name='حداقل موجودی')),
                ('aisle', models.IntegerField(blank=True, null=True, verbose_name='راهرو')),
                ('row', models.IntegerField(blank=True, null=True, verbose_name='ردیف')),
                ('bin', models.IntegerField(blank=True, null=True, verbose_name='قفسه')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='مکان')),
                ('stockItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='نام قطعه')),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': {('stockItem', 'location')},
            },
        ),
        migrations.CreateModel(
            name='StopCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد توقف')),
                ('stopDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح توقف')),
            ],
            options={
                'db_table': 'stopcode',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('fullName', models.CharField(max_length=50, verbose_name='مشخصات کامل')),
                ('personalCode', models.CharField(max_length=50, verbose_name='کد پرسنلی')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='ایمیل')),
                ('tel1', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن')),
                ('tel2', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن 2')),
                ('addr1', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('addr2', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس 2')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='کشور')),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپستی')),
                ('hourlyRate', models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ دستمزد ساعتی')),
                ('defaultLoginLocation', models.FloatField(blank=True, choices=[(1, 'داشبورد'), (2, 'درخواستهای انتسابی به من'), (3, 'صندوق ورودی پیامها'), (4, 'درخواست')], null=True, verbose_name='صفحه پیش فرض')),
                ('profileImage', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('userStatus', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sysusers',
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskGroupName', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام گروه')),
            ],
            options={
                'db_table': 'taskgroup',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTypes', models.IntegerField(blank=True, choices=[(1, 'عمومی'), (2, 'متنی'), (3, 'متریک')], null=True, verbose_name='انتخاب نوع فعالیت')),
                ('taskDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('taskResult', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('taskStartDate', models.DateField(blank=True, null=True, verbose_name=' تاریخ شروع')),
                ('taskStartTime', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان شروع')),
                ('taskTimeEstimate', models.FloatField(blank=True, null=True, verbose_name='زمان تقریبی( به ساعت)')),
                ('taskDateCompleted', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ تکمیل')),
                ('taskTimeCompleted', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان پایان')),
                ('taskTimeSpent', models.FloatField(blank=True, null=True, verbose_name='زمان صرف شده')),
                ('taskCompletionNote', models.CharField(blank=True, max_length=100, null=True, verbose_name='یادداشت تکمیلی')),
                ('taskAssignedToUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedToUserTask', to='cmms.sysuser', verbose_name='اختصاص به کاربر')),
                ('taskCompletedByUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompleteUserTask', to='cmms.sysuser', verbose_name='کاربر تکمیل کننده')),
                ('taskMetrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='testuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.CharField(max_length=50, verbose_name='مشخصات کامل')),
            ],
            options={
                'db_table': 'testuser',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGroupCode', models.CharField(max_length=50, verbose_name='کد')),
                ('userGroupName', models.CharField(max_length=50, verbose_name='نام')),
                ('userGroupZarib', models.FloatField(blank=True, null=True, verbose_name='ضریب حضور')),
                ('userGroupZaribTamir', models.FloatField(blank=True, null=True, verbose_name='ضریب تعمیر')),
                ('userGroupZaribService', models.FloatField(blank=True, null=True, verbose_name='ضریب سرویس')),
                ('userGroupZaribProject', models.FloatField(blank=True, null=True, verbose_name='ضریب پروژه')),
                ('userGroupIsPartOF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.usergroup', verbose_name='زیرمجموعه')),
                ('userUserLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='واحد')),
            ],
            options={
                'db_table': 'usergroup',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woStatus', models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست')),
                ('woPriority', models.IntegerField(blank=True, choices=[(1, 'خیلی زیاد'), (2, 'زیاد'), (3, 'متوسط'), (4, 'پایین'), (5, 'خیلی پایین')], null=True, verbose_name='اولویت')),
                ('requiredCompletionDate', models.DateField(blank=True, default=datetime.datetime.now, verbose_name=' تاریخ اتمام مورد نیاز')),
                ('requiredCompletionTime', models.TimeField(blank=True, default=datetime.datetime.now, verbose_name='زمان')),
                ('summaryofIssue', models.CharField(blank=True, max_length=200, null=True, verbose_name='خلاصه مشکل')),
                ('workInstructions', models.CharField(blank=True, max_length=50, null=True, verbose_name='دستورالعمل')),
                ('estimatedLabor', models.FloatField(blank=True, null=True, verbose_name='ساعت کار مورد نیاز (تخمینی)')),
                ('actualLabor', models.FloatField(blank=True, null=True, verbose_name='ساعت کار واقعی')),
                ('datecreated', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ ایجاد')),
                ('timecreated', models.TimeField(blank=True, null=True, verbose_name='زمان ایجاد')),
                ('dateCompleted', models.DateField(blank=True, null=True, verbose_name=' تاریخ تکمیل(تخمینی)')),
                ('timeCompleted', models.TimeField(blank=True, default=datetime.datetime.now, verbose_name='زمان تکمیل(تخمین')),
                ('account', models.CharField(blank=True, max_length=50, null=True, verbose_name='حساب')),
                ('chargeDepartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='دپارتمان مسوول')),
                ('completionNotes', models.CharField(blank=True, max_length=200, null=True, verbose_name='اطلاعات تکمیلی')),
                ('problemBrief', models.CharField(blank=True, max_length=50, null=True, verbose_name='مشکل (خلاصه)')),
                ('rootCause', models.CharField(blank=True, max_length=50, null=True, verbose_name='علت اصلی')),
                ('solution', models.CharField(blank=True, max_length=50, null=True, verbose_name='راه حل')),
                ('adminNote', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات مدیر')),
                ('allTriggerFire', models.BooleanField(blank=True, default=True, verbose_name='تمامی محرک ها')),
                ('isScheduling', models.BooleanField(blank=True, default=False)),
                ('isEM', models.BooleanField(blank=True, default=False, verbose_name='درخوسات ناخواسته یا EM')),
                ('estimatedCompilation', models.IntegerField(blank=True, default=1, null=True, verbose_name='زمان تخمینی تکمیل(روز)')),
                ('creatNewWO', models.BooleanField(blank=True, default=False, verbose_name='ایجاد درخواست جدید در صورت بسته نشدن درخوسات قبلی')),
                ('running', models.BooleanField(blank=True, default=False, verbose_name='در حال اجرا')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('visibile', models.BooleanField(blank=True, default=True)),
                ('isUpdating', models.BooleanField(blank=True, default=False)),
                ('isPm', models.BooleanField(default=False)),
                ('woTags', models.TextField(blank=True, null=True)),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.project', verbose_name='پروژه')),
                ('RequestedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestedUser', to='cmms.sysuser', verbose_name='درخواست کننده')),
                ('assignedToUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedToUser', to='cmms.sysuser', verbose_name='اختصاص به کاربر')),
                ('completedByUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completedByUser', to='cmms.sysuser', verbose_name='تکمیل درخواست توسط کاربر')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder', verbose_name='زیر مجموعه')),
                ('maintenanceType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.maintenancetype', verbose_name='نوع نگهداری')),
                ('woActionCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woActionCode', to='cmms.actioncode', verbose_name='کد اقدام')),
                ('woAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('woCauseCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woCauseCode', to='cmms.causecode', verbose_name='کد علت')),
                ('woProblemCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woProblemCode', to='cmms.problemcode', verbose_name='کد مشکل')),
                ('woStopCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woStopCode', to='cmms.stopcode', verbose_name='کد توقف')),
            ],
            options={
                'db_table': 'workorder',
            },
        ),
        migrations.CreateModel(
            name='WorkorderUserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woNotifOnAssignment', models.BooleanField(default=True, verbose_name='پیام رسانی هنگام ایجاد درخواست')),
                ('woNotifOnStatusChange', models.BooleanField(default=False, verbose_name='پیام رسانی هنگام تغییر')),
                ('woNotifOnCompletion', models.BooleanField(default=False, verbose_name='پیام رسانی هنگام تکمیل')),
                ('woNotifOnTaskCompleted', models.BooleanField(default=False, verbose_name='پیام رسانی هنگام تکمیل وظیفه')),
                ('woNotifOnOnlineOffline', models.BooleanField(default=False, verbose_name='پیام رسانی هنگام آنلاین آفلاین شدن')),
                ('woNotifUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر')),
                ('woNotifWorkorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder')),
            ],
            options={
                'db_table': 'workorderusernotification',
            },
        ),
        migrations.CreateModel(
            name='WorkorderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worordertaskrelated', to='cmms.tasks')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worordertaskwordrelated', to='cmms.workorder')),
            ],
            options={
                'db_table': 'workordertask',
            },
        ),
        migrations.CreateModel(
            name='WorkorderMeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woMeterReadingMeterReading', models.FloatField(default=0.0, verbose_name='meter reading')),
                ('timestamp', models.DateField(blank=True, default=datetime.datetime.now)),
                ('woMeterReadingLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('woMeterReadingMeterReadingUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woMeterReadingMeterReadingUnit', to='cmms.metercode', verbose_name='واحد اندازه گیری')),
                ('woMeterReadingworkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder', verbose_name='سفارش کار')),
            ],
            options={
                'db_table': 'workordermeterreading',
            },
        ),
        migrations.CreateModel(
            name='WorkorderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woFile', models.FileField(max_length=200, upload_to='documents/')),
                ('woFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('woFileworkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder')),
            ],
            options={
                'db_table': 'workorderfile',
            },
        ),
        migrations.CreateModel(
            name='Waranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warantyType', models.IntegerField(blank=True, choices=[(1, 'ساده'), (2, 'قابل تمدید')], null=True, verbose_name='نوع گارانتی')),
                ('warantyUsageTermType', models.IntegerField(blank=True, choices=[(1, 'تاریخ'), (2, 'اندازه گیری'), (3, 'ساعت تولید')], null=True, verbose_name='شرایط استفاده از گارانتی')),
                ('warantyDataAdded', models.DateField(auto_now_add=True, verbose_name=' تاریخ  ثبت')),
                ('warantyExpirationDate', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انقضا')),
                ('warantyQnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('warantyMeterReadingValueLimit', models.IntegerField(blank=True, null=True, verbose_name='مقدار محدودکننده؟؟؟')),
                ('warantyMeterReadingUnit', models.IntegerField(blank=True, choices=[(1, 'Cycles (cycles)'), (2, 'Cycles (g)'), (3, 'Hours (h)'), (4, 'Kilometers (km)'), (5, 'Kilopascals (kPa)'), (6, 'Litres (l)'), (7, 'Meters (m)'), (8, 'Miles (mi)'), (9, 'Pounds per square inch (PSI)'), (10, 'ProductionHours (ph)'), (11, 'Revolutions (rev)')], null=True, verbose_name='واحد اندازه گیری')),
                ('warantyCertificationNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهی')),
                ('warantyDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('warantyLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='مکان')),
                ('warantyProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business', verbose_name='تامین کننده')),
            ],
            options={
                'db_table': 'waranty',
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupUserGroups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.usergroup')),
                ('userUserGroups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser')),
            ],
            options={
                'db_table': 'usergroups',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFile', models.FileField(upload_to='documents/')),
                ('userFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('userFileUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser')),
            ],
            options={
                'db_table': 'userfile',
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCertificationName', models.CharField(max_length=50, verbose_name='عنوان')),
                ('userCertificationType', models.IntegerField(blank=True, choices=[(1, 'نوع مدرک 1'), (2, 'نوع مدرک 2'), (3, 'نوع مدرک 3')], null=True, verbose_name='نوع مدرک')),
                ('userCertificationDesc', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('userCertificationStart', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار از')),
                ('userCertificationEnd', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار از')),
                ('userCertificationUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser')),
            ],
            options={
                'db_table': 'usercertification',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTemplateTypes', models.IntegerField(blank=True, choices=[(1, 'عمومی'), (2, 'متنی'), (3, 'متریک')], null=True, verbose_name='انتخاب نوع فعالیت')),
                ('taskTemplateDescription', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('taskTemplateTimeEstimate', models.FloatField(blank=True, null=True, verbose_name='زمان تقریبی( به ساعت)')),
                ('taskTemplateMetrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری')),
                ('taskTemplateTaskGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskgroup', to='cmms.taskgroup', verbose_name='متعلق به')),
            ],
            options={
                'db_table': 'tasktemplate',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='workOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompleteUserTask', to='cmms.workorder'),
        ),
        migrations.CreateModel(
            name='TaskGroupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskGroupFile', models.FileField(upload_to='documents/')),
                ('taskGroupFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('taskGroupFileTaskGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.taskgroup')),
            ],
            options={
                'db_table': 'taskgroupfile',
            },
        ),
        migrations.CreateModel(
            name='TaskGroupAssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includeSubCategory', models.BooleanField(blank=True, default=True, verbose_name='شامل زیر مجموعه دسته بندی ها')),
                ('TaskGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.taskgroup')),
                ('assetCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetcategory', verbose_name='دسته دارایی')),
            ],
            options={
                'db_table': 'taskgroupassetcategory',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schChoices', models.IntegerField(choices=[(0, 'با تکرار زمان'), (1, 'بر اساس مقدار'), (2, 'رویداد محور')], default=0, null=True, verbose_name='اولویت')),
                ('schHowOften', models.IntegerField(choices=[(1, 'ساعتی'), (2, 'روزانه'), (3, 'هفتگی'), (4, 'ماهانه'), (5, 'سالانه')], default=1, null=True, verbose_name='تکرار')),
                ('schHourRep', models.IntegerField(blank=True, null=True, verbose_name='ساعت')),
                ('schHourIsFixed', models.BooleanField(blank=True, choices=[(True, 'ثابت'), (False, 'شناور')], default=True, verbose_name='ثابت')),
                ('schDailyRep', models.IntegerField(blank=True, null=True, verbose_name='روز')),
                ('schDayIsFixed', models.BooleanField(blank=True, choices=[(True, 'ثابت'), (False, 'شناور')], default=True, verbose_name='ثابت')),
                ('schWeeklyRep', models.IntegerField(blank=True, null=True, verbose_name='هفته')),
                ('isSunday', models.BooleanField(blank=True, default=True, verbose_name='یکشنبه')),
                ('isMonday', models.BooleanField(blank=True, default=True, verbose_name='دوشنبه')),
                ('isTuesday', models.BooleanField(blank=True, default=True, verbose_name='سه شنبه')),
                ('isWednenday', models.BooleanField(blank=True, default=True, verbose_name='چهارشنبه')),
                ('isThursday', models.BooleanField(blank=True, default=True, verbose_name='پنجشنبه')),
                ('isFriday', models.BooleanField(blank=True, default=True, verbose_name='جمعه')),
                ('isSaturday', models.BooleanField(blank=True, default=True, verbose_name='شنبه')),
                ('schMonthlyRep', models.IntegerField(blank=True, null=True, verbose_name='ماه')),
                ('schDayofMonthlyRep', models.IntegerField(blank=True, null=True, verbose_name='روز')),
                ('schMonthIsFixed', models.BooleanField(blank=True, choices=[(True, 'ثابت'), (False, 'شناور')], verbose_name='ثابت')),
                ('schYearlyRep', models.IntegerField(blank=True, null=True, verbose_name='ماه')),
                ('schMonthOfYearRep', models.IntegerField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='ماه')),
                ('schDayOfMonthOfYearRep', models.IntegerField(blank=True, null=True, verbose_name='روز')),
                ('schYearIsFixed', models.BooleanField(blank=True, choices=[(True, 'ثابت'), (False, 'شناور')], default=True, verbose_name='ثابت')),
                ('shStartDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('shEndDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('shHasEndDate', models.BooleanField(blank=True, verbose_name='تاریخ انقضا')),
                ('shMeterReadingEvreyQnty', models.FloatField(blank=True, default=0, null=True, verbose_name='هر')),
                ('shMeterReadingStartAt', models.FloatField(blank=True, null=True, verbose_name='مقدار شروع')),
                ('shMeterReadingEndBy', models.FloatField(blank=True, null=True, verbose_name='مقذار نهایی')),
                ('schMeterReadingIsFixed', models.BooleanField(blank=True, choices=[(True, 'ثابت'), (False, 'شناور')], default=True, verbose_name='ثابت')),
                ('schHasEndReading', models.BooleanField(default=False, verbose_name='مقدار پایانی')),
                ('shMeterReadingHasTiming', models.BooleanField(default=True)),
                ('shMeterReadingWhenQnty', models.FloatField(blank=True, null=True, verbose_name='زمان')),
                ('shMetricComparison', models.IntegerField(blank=True, choices=[(0, 'بزرگتر از'), (1, 'کوچکتر از')], null=True)),
                ('schnextTime', models.DateTimeField(blank=True, null=True)),
                ('schTimestamp', models.DateTimeField(auto_now_add=True)),
                ('schTriggerTime', models.IntegerField(blank=True, null=True, verbose_name='زمان راه اندازی')),
                ('schCreateOnStartDate', models.BooleanField(default=False, verbose_name='ساختن در زمان شروع')),
                ('shMeterNextVal', models.FloatField(blank=True, null=True, verbose_name='مقدار بعدی')),
                ('schAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schAsset', to='cmms.asset')),
                ('schEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.events')),
                ('schNextWo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schnextWo', to='cmms.workorder')),
                ('shMeterReadingMetrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_shMeterReadingMetrics', to='cmms.metercode', verbose_name='واحد اندازه گیری')),
                ('shMeterReadingWhenMetric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_meter_when', to='cmms.metercode', verbose_name='واحد اندازه گیری')),
                ('workOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseRequestStatus', models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست')),
                ('PurchaseRequestAssetName', models.CharField(blank=True, max_length=100, null=True, verbose_name='مشخصات')),
                ('PurchaseRequestMoreInfo', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات بیشتر')),
                ('PurchaseRequestAssetNotInInventory', models.CharField(blank=True, max_length=100, null=True, verbose_name='ناموجود در انبار؟ اطلاعات بیشتری شرح دهید')),
                ('PurchaseRequestAssetQty', models.FloatField(blank=True, null=True, verbose_name='تعداد')),
                ('PurchaseRequestAssetQtyNot', models.FloatField(blank=True, null=True, verbose_name='کمیت')),
                ('PurchaseRequestAssetNot', models.BooleanField(default=False, verbose_name='در صورت عدم تهیه تولید دچار وقفه میشود')),
                ('PurchaseRequestNotInList', models.BooleanField(default=False)),
                ('PurchaseRequestDateTo', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='مهلت تا تاریخ')),
                ('PurchaseRequestDateFrom', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ درخواست')),
                ('settingTimestamp', models.DateTimeField(auto_now_add=True)),
                ('PurchaseRequestAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedAsset', to='cmms.asset')),
                ('PurchaseRequestAuthUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestAuthUser', to='cmms.sysuser', verbose_name='کاربر مجاز')),
                ('PurchaseRequestRequestedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestdUser', to='cmms.sysuser', verbose_name='کاربر درخواست کننده')),
                ('PurchaseRequestWO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedWO', to='cmms.workorder')),
            ],
            options={
                'db_table': 'purchaserequest',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDateOrdered', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ سفارش')),
                ('purchasePriceTotla', models.FloatField(blank=True, null=True, verbose_name='قیمت تمام شده')),
                ('purchaseCurrency', models.IntegerField(blank=True, choices=[(0, 'Us Dollar'), (1, 'Rial')], null=True, verbose_name='واحد پول')),
                ('purchaseDateRecieved', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('purchaseDateofExpire', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('purchaseAssetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('purchaseUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر درخواست کننده')),
                ('purchasedFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business', verbose_name='خرید از')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.project', verbose_name='دارایی')),
                ('ProjectUserUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر ')),
            ],
            options={
                'db_table': 'projectuser',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectFile', models.FileField(upload_to='documents/')),
                ('projectFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('projectFileProjectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.project')),
            ],
            options={
                'db_table': 'projectfile',
            },
        ),
        migrations.CreateModel(
            name='PartWaranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warantyType', models.IntegerField(blank=True, choices=[(1, 'ساده'), (2, 'قابل تمدید')], null=True, verbose_name='نوع گارانتی')),
                ('warantyUsageTermType', models.IntegerField(blank=True, choices=[(1, 'تاریخ'), (2, 'اندازه گیری'), (3, 'ساعت تولید')], null=True, verbose_name='شرایط استفاده از گارانتی')),
                ('warantyDataAdded', models.DateField(auto_now_add=True, verbose_name=' تاریخ  ثبت')),
                ('warantyExpirationDate', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انقضا')),
                ('warantyQnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('warantyMeterReadingValueLimit', models.IntegerField(blank=True, null=True, verbose_name='مقدار محدودکننده؟؟؟')),
                ('warantyMeterReadingUnit', models.IntegerField(blank=True, choices=[(1, 'Cycles (cycles)'), (2, 'Cycles (g)'), (3, 'Hours (h)'), (4, 'Kilometers (km)'), (5, 'Kilopascals (kPa)'), (6, 'Litres (l)'), (7, 'Meters (m)'), (8, 'Miles (mi)'), (9, 'Pounds per square inch (PSI)'), (10, 'ProductionHours (ph)'), (11, 'Revolutions (rev)')], null=True, verbose_name='واحد اندازه گیری')),
                ('warantyCertificationNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهی')),
                ('warantyDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('warantyProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business', verbose_name='تامین کننده')),
                ('warantyStockItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='نام قطعه')),
            ],
            options={
                'db_table': 'partwaranty',
            },
        ),
        migrations.CreateModel(
            name='PartUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartUserPartId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='قطعه')),
                ('PartUserUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر ')),
            ],
            options={
                'db_table': 'partuser',
            },
        ),
        migrations.CreateModel(
            name='PartPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDateOrdered', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ سفارش')),
                ('purchasePriceTotla', models.FloatField(blank=True, default=0.0, null=True, verbose_name='قیمت تمام شده')),
                ('purchaseCurrency', models.IntegerField(blank=True, choices=[(0, 'Us Dollar'), (1, 'Rial')], null=True, verbose_name='واحد پول')),
                ('purchaseDateRecieved', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('purchaseDateofExpire', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('purchaseQuantityReceived', models.FloatField(default=0.0, verbose_name='تعداد')),
                ('purchasePricePerUnit', models.FloatField(default=0.0, verbose_name='قیمت واحد')),
                ('purchasePartId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='قطعه')),
                ('purchaseStock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='انبار قطعه')),
                ('purchaseUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر درخواست کننده')),
                ('purchasedFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business', verbose_name='خرید از')),
            ],
            options={
                'db_table': 'partpurchase',
            },
        ),
        migrations.CreateModel(
            name='PartFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partFile', models.FileField(max_length=200, upload_to='documents/')),
                ('partFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('partFilePartId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part')),
            ],
            options={
                'db_table': 'partfile',
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('priority', models.IntegerField(null=True, verbose_name='اولویت')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.partcategory', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'partcategory',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='partCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dasdadassa', to='cmms.partcategory', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='MiscCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscCoastdescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('estimatedQnty', models.FloatField(blank=True, default=0.0, null=True, verbose_name='مقدار تخمینی')),
                ('estimatedUnitCoast', models.FloatField(blank=True, default=0.0, null=True, verbose_name='هزینه تخمینی بازای واحد')),
                ('estimatedTotalCoast', models.FloatField(blank=True, default=0.0, null=True, verbose_name='هزینه تخمینی کلی')),
                ('qnty', models.FloatField(blank=True, default=0.0, null=True, verbose_name='مقدار واقعی')),
                ('actualUnitCoast', models.FloatField(blank=True, default=0.0, null=True, verbose_name='هزینه واحد')),
                ('actualTotlaCoast', models.FloatField(blank=True, default=0.0, null=True, verbose_name='هزینه کل')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('miscCoastIndividual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscCoastIndividuals', to='cmms.business', verbose_name='پیمانکار')),
                ('miscCoastType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscCoastWorkorder', to='cmms.misccostcode', verbose_name='نوع')),
                ('miscCoastWorkorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder')),
            ],
            options={
                'db_table': 'misccoast',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgPririty', models.IntegerField(blank=True, choices=[(1, 'خیلی زیاد'), (2, 'زیاد'), (3, 'متوسط'), (4, 'پایین'), (5, 'خیلی پایین')], null=True, verbose_name='پیامهای سیستمی')),
                ('messageStatus', models.IntegerField(choices=[(3, 'read'), (2, 'unread')], verbose_name='وضعیت')),
                ('sentTime', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع')),
                ('Message', models.TextField(blank=True, null=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='cmms.sysuser', verbose_name='از:')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='cmms.sysuser', verbose_name='به:')),
                ('workOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workordermsg', to='cmms.workorder', verbose_name='به:')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.machinecategory', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'machinecategory',
            },
        ),
        migrations.CreateModel(
            name='KpiException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.stopcode', unique=True, verbose_name='کد توقف')),
            ],
            options={
                'db_table': 'kpiexception',
            },
        ),
        migrations.CreateModel(
            name='EquipSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EqSettingTimestamp', models.DateTimeField(auto_now_add=True)),
                ('EqSettingAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset')),
            ],
            options={
                'db_table': 'equipsetting',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCostSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingEqTimestamp', models.DateTimeField(auto_now_add=True)),
                ('settingEqAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset')),
            ],
            options={
                'db_table': 'equipmentcostSetting',
            },
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='پرسنل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='نام قطعه')),
            ],
            options={
                'db_table': 'businessuser',
            },
        ),
        migrations.CreateModel(
            name='BusinessPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessPartBusinessType', models.IntegerField(blank=True, choices=[(0, 'تامین کننده'), (1, 'سارننده'), (2, 'خدماتی'), (3, 'مالک'), (4, 'مشتری')], null=True, verbose_name='نوع کسب و کار')),
                ('businessPartSupplierPartNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='پارت نامبر تامین کننده')),
                ('businessPartCatalog', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته بندی')),
                ('businessPartisDefault', models.BooleanField(default=False, verbose_name='تامین کننده مورد علاقه')),
                ('businessPartVendorPrice', models.FloatField(blank=True, null=True, verbose_name='قیمت تامین کننده')),
                ('BusinessPartPart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='نام قطعه')),
                ('businessPartBusiness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business', verbose_name='تامین کننده')),
            ],
            options={
                'db_table': 'businesspart',
            },
        ),
        migrations.CreateModel(
            name='BusinessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessFile', models.FileField(upload_to='documents/')),
                ('businessFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('businessFileBusinessId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business')),
            ],
            options={
                'db_table': 'businessfiles',
            },
        ),
        migrations.CreateModel(
            name='BusinessAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessAssetBusinessType', models.IntegerField(blank=True, choices=[(0, 'تامین کننده'), (1, 'سارننده'), (2, 'خدماتی'), (3, 'مالک'), (4, 'مشتری')], null=True, verbose_name='نوع کسب و کار')),
                ('businessAssetSupplierPartNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='پارت نامبر تامین کننده')),
                ('businessAssetCatalog', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته بندی')),
                ('businessAssetisDefault', models.BooleanField(default=False, verbose_name='تامین کننده مورد علاقه')),
                ('businessAssetVendorPrice', models.FloatField(blank=True, null=True, verbose_name='قیمت تامین کننده')),
                ('BusinessAssetAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='نام دارایی')),
                ('businessAssetBusiness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.business', verbose_name='کسب و کار')),
            ],
            options={
                'db_table': 'businessasset',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='مکان')),
                ('stockItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='نام قطعه')),
            ],
            options={
                'db_table': 'bom',
            },
        ),
        migrations.CreateModel(
            name='AssetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetUserAssetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('AssetUserUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر ')),
            ],
            options={
                'db_table': 'assetuser',
            },
        ),
        migrations.CreateModel(
            name='AssetPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetPartQnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('assetPartDescription', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح')),
                ('assetPartAssetid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='نام دارایی')),
                ('assetPartBOMGroupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.bomgroup', verbose_name='گروه')),
                ('assetPartPid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='نام قطعه')),
            ],
            options={
                'db_table': 'assetpart',
            },
        ),
        migrations.AddField(
            model_name='assetmetertemplate',
            name='assetMeterTemplateMeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='کمیت اندازه گیری'),
        ),
        migrations.CreateModel(
            name='AssetMeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetMeterMeterReading', models.FloatField(default=0.0, verbose_name='meter reading')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assetMeterLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('assetMeterMeterReadingUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری')),
                ('assetWorkorderMeterReading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder', verbose_name='درخواست')),
            ],
            options={
                'db_table': 'assetmeterreading',
            },
        ),
        migrations.CreateModel(
            name='AssetLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetOfflineFrom', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ خاموشی')),
                ('assetOfflineFromTime', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان خاموشی')),
                ('assetOfflineAdditionalInfo', models.TextField(blank=True, null=True, verbose_name='اطلاعات اضافی')),
                ('assetEventDescription', models.TextField(blank=True, null=True, verbose_name='شرح رویداد')),
                ('assetOnlineFrom', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ شروع')),
                ('assetOnlineFromTime', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='زمان شروع')),
                ('assetOnlineStatus', models.IntegerField(blank=True, choices=[(0, 'در حال تولید'), (1, 'آماده به کار')], null=True, verbose_name='وضعیت')),
                ('assetOnlineAdditionalInfo', models.TextField(blank=True, null=True, verbose_name='اطلاعات اضافی')),
                ('assetOnlineProducteHourAffected', models.IntegerField(blank=True, default=0, null=True, verbose_name='ساعت وقفه در تولید')),
                ('assetCheckEvent', models.BooleanField(default=False, verbose_name='ایجاد رویداد')),
                ('assetCauseCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetlifeCauseCode', to='cmms.causecode', verbose_name='کد علت')),
                ('assetEventType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.events', verbose_name='نوع رویداد')),
                ('assetLifeAssetid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='نام دارایی')),
                ('assetOfflineStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.offlinestatus', verbose_name='وضعیت')),
                ('assetSetOfflineByUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offlineUser', to='cmms.sysuser', verbose_name='کاربر')),
                ('assetSetOnlineByUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineUser', to='cmms.sysuser', verbose_name='کاربر')),
                ('assetStopCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetStopCode', to='cmms.stopcode', verbose_name='کد توقف')),
                ('assetWOAssoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder', verbose_name='درخواست مرتبط')),
            ],
            options={
                'db_table': 'assetlife',
            },
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetFile', models.FileField(max_length=200, upload_to='documents/')),
                ('assetFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('assetFileAssetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset')),
            ],
            options={
                'db_table': 'assetfile',
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetEventAdditionalDescription', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات تکمیلی')),
                ('AssetEventDateSubmitted', models.DateField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('AssetEventAssetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('AssetEventEventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.events', verbose_name='نوع رویداد')),
            ],
            options={
                'db_table': 'assetevent',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='assetCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms.assetcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetIsLocatedAt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='cmms.asset', verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetIsPartOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms.asset', verbose_name='زیر مجموعه'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetMachineCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.machinecategory', verbose_name='نوع دستگاه'),
        ),
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingTimestamp', models.DateTimeField(auto_now_add=True)),
                ('settingAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset')),
            ],
            options={
                'db_table': 'adminsetting',
            },
        ),
        migrations.CreateModel(
            name='WorkorderPert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpPertTime', models.FloatField(default=0, null=True, verbose_name='مقدار پرت (دقیقه)')),
                ('woPertPert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.pertcode', verbose_name='کد پرت')),
                ('woPertWorkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder', verbose_name='دستور کار')),
            ],
            options={
                'db_table': 'workorderpert',
                'unique_together': {('woPertWorkorder', 'woPertPert')},
            },
        ),
        migrations.CreateModel(
            name='WorkorderPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woPartPlannedQnty', models.FloatField(blank=True, default=0.0, null=True, verbose_name='کمیت پیشنهادی')),
                ('woPartActulaQnty', models.FloatField(blank=True, default=0.0, null=True, verbose_name='کمیت واقعی')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('woPartStock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.stock', verbose_name='انبار')),
                ('woPartWorkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.workorder', verbose_name='سفارش کار')),
            ],
            options={
                'db_table': 'workorderpart',
                'unique_together': {('woPartWorkorder', 'woPartStock')},
            },
        ),
        migrations.CreateModel(
            name='UserGroupMaintenanceZarib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaribUGMZ', models.FloatField(blank=True, null=True, verbose_name='ضریب پروژه')),
                ('groupUGMZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.usergroup')),
                ('maintenanceTypeUGMZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.maintenancetype', verbose_name='نوع نگهداری')),
            ],
            options={
                'db_table': 'usergroupmaintenancezarib',
                'unique_together': {('groupUGMZ', 'maintenanceTypeUGMZ')},
            },
        ),
        migrations.CreateModel(
            name='BOMGroupPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOMGroupPartQnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('BOMGroupPartBOMGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.bomgroup', verbose_name='گروه')),
                ('BOMGroupPartPart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.part', verbose_name='قطعه')),
            ],
            options={
                'db_table': 'bomgrouppart',
                'unique_together': {('BOMGroupPartPart', 'BOMGroupPartBOMGroup')},
            },
        ),
        migrations.CreateModel(
            name='BOMGroupAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOMGroupAssetAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('BOMGroupAssetBOMGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.bomgroup', verbose_name='گروه')),
            ],
            options={
                'db_table': 'bomgroupasset',
                'unique_together': {('BOMGroupAssetAsset', 'BOMGroupAssetBOMGroup')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ حضور')),
                ('attendanceTime', models.FloatField(default=8, verbose_name='زمان حضور')),
                ('Ezafekar', models.FloatField(default=8, verbose_name='اضافه کار')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='نام کاربر')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('name', 'datecreated')},
            },
        ),
        migrations.CreateModel(
            name='AssetTypeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingEqTimestamp', models.DateTimeField(auto_now_add=True)),
                ('settingEqAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetcategory', verbose_name='دسته دارایی')),
                ('settingLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='مکان')),
            ],
            options={
                'db_table': 'assettypesetting',
                'unique_together': {('settingEqAsset', 'settingLocation')},
            },
        ),
    ]
