# Generated by Django 3.2.6 on 2021-08-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscCostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscCostCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد')),
                ('miscCostDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='َشرح')),
            ],
            options={
                'db_table': 'misccostcode',
            },
        ),
        migrations.AddField(
            model_name='misccost',
            name='miscCoastType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscCoastWorkorder', to='cmms.misccostcode', verbose_name='نوع'),
        ),
    ]
