# Generated by Django 3.2.6 on 2021-11-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partfile',
            name='partFile',
            field=models.FileField(max_length=200, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='taskTemplateMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
