# Generated by Django 3.2.6 on 2021-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='description',
            field=models.CharField(default=1, max_length=50, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
