# Generated by Django 3.2.6 on 2021-11-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcategory',
            name='name',
        ),
    ]
