# Generated by Django 2.0.2 on 2021-01-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorderpart',
            unique_together=set(),
        ),
    ]
