# Generated by Django 3.2.6 on 2021-11-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmeterreading',
            name='assetMeterLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی'),
        ),
        migrations.AddField(
            model_name='assetmeterreading',
            name='assetMeterMeterReading',
            field=models.FloatField(default=0.0, verbose_name='meter reading'),
        ),
        migrations.AddField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
