# Generated by Django 3.2.6 on 2022-01-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskResult',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='نتیجه'),
        ),
    ]
