# Generated by Django 3.2.6 on 2023-04-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetCadFile2',
            new_name='AssetCadFile',
        ),
    ]
