# Generated by Django 3.2.6 on 2021-11-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiexception',
            name='stopcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmms.stopcode', unique=True),
            preserve_default=False,
        ),
    ]
