# Generated by Django 3.2.6 on 2022-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmetertemplate',
            name='assetMeterTemplateDesc2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شرح'),
        ),
    ]
