# Generated by Django 3.2.6 on 2023-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcadcoordination',
            name='z',
        ),
    ]
