# Generated by Django 3.2.6 on 2022-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_alter_tasks_taskresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDateCompleted',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
    ]
