# Generated by Django 3.2.6 on 2021-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_remove_partcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
