# Generated by Django 3.2.6 on 2021-11-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_auto_20211127_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterLocation',
        ),
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterMeterReading',
        ),
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
        ),
    ]
