# Generated by Django 3.2.6 on 2023-04-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_rename_assetcadfile2_assetcadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcadfile',
            name='assetCadFile',
            field=models.FloatField(),
        ),
    ]
