# Generated by Django 3.2.6 on 2022-01-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_assetmetertemplate_assetmetertemplatedesc2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmetertemplate',
            name='assetMeterTemplateDesc2',
        ),
    ]
