# Generated by Django 2.0.2 on 2021-05-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_assettypesetting_settinglocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettypesetting',
            name='settingEqAsset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.AssetCategory', verbose_name='دسته دارایی'),
        ),
        migrations.AlterUniqueTogether(
            name='assettypesetting',
            unique_together={('settingEqAsset', 'settingLocation')},
        ),
    ]
