# Generated by Django 3.2.6 on 2021-11-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_auto_20211122_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metercode',
            name='meterAbbr',
        ),
        migrations.RemoveField(
            model_name='metercode',
            name='meterCode',
        ),
    ]
