# Generated by Django 2.0.2 on 2021-01-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_auto_20210124_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorderpart',
            unique_together={('woPartWorkorder', 'woPartStock')},
        ),
    ]
