# Generated by Django 3.2.6 on 2021-11-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_partcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
