# Generated by Django 2.0.2 on 2021-01-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_auto_20210125_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='workOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workordermsg', to='cmms.WorkOrder', verbose_name='به:'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='isEM',
            field=models.BooleanField(default=False, verbose_name='درخوسات ناخواسته یا EM'),
        ),
    ]
