# Generated by Django 3.2.6 on 2021-11-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_auto_20211122_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='metercode',
            name='meterAbbr',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='اختصار'),
        ),
        migrations.AddField(
            model_name='metercode',
            name='meterCode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد'),
        ),
    ]
