# Generated by Django 3.2.6 on 2022-01-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_remove_assetmetertemplate_assetmetertemplatedesc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMeterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchMeterGroupName', models.CharField(max_length=50, unique=True, verbose_name='نام گروه اندازه گیری')),
            ],
            options={
                'db_table': 'batchmetergroup',
            },
        ),
    ]
