# Generated by Django 3.2.6 on 2023-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_assetcadcoordination_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcadcoordination',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
