# Generated by Django 3.2.6 on 2022-01-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_alter_tasks_taskdatecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
