# Generated by Django 3.2.6 on 2021-08-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_remove_misccost_misccoastindividual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
        ),
    ]
