# Generated by Django 3.2.6 on 2021-11-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_partcategory_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartCategory',
        ),
    ]
