# Generated by Django 3.2.6 on 2021-11-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_auto_20211122_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metercode',
            name='meterDescription',
        ),
    ]
