# Generated by Django 2.0.2 on 2021-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_auto_20210527_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد'),
        ),
    ]
