# Generated by Django 3.2.6 on 2022-01-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_alter_assetmeterreading_assetmetermeterreadingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
    ]
