# Generated by Django 3.2.6 on 2022-01-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_batchmetergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmetertemplate',
            name='assetMeterTemplateAsset',
        ),
    ]
