# Generated by Django 2.0.2 on 2021-01-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_auto_20210128_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDescription',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات'),
        ),
    ]
