# Generated by Django 3.2.6 on 2023-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_alter_assetcadcoordination_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcadcoordination',
            name='z2',
            field=models.FloatField(default=0),
        ),
    ]
