# Generated by Django 2.0.2 on 2021-07-15 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_auto_20210527_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseRequestAssetName', models.CharField(blank=True, max_length=100, null=True, verbose_name='مشخصات')),
                ('PurchaseRequestMoreInfo', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات بیشتر')),
                ('PurchaseRequestAssetNotInInventory', models.CharField(blank=True, max_length=100, null=True, verbose_name='ناموجود در انبار؟ اطلاعات بیشتری شرح دهید')),
                ('PurchaseRequestAssetQty', models.FloatField(blank=True, max_length=100, null=True, verbose_name='کمیت')),
                ('PurchaseRequestNotInList', models.BooleanField(default=False)),
                ('PurchaseRequestAssetQtyNot', models.BooleanField(default=False, verbose_name='در صورت عدم تهیه تولید دچار وقفه میشود')),
                ('PurchaseRequestDate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='مهلت تا تاریخ')),
                ('settingTimestamp', models.DateTimeField(auto_now_add=True)),
                ('PurchaseRequestAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedAsset', to='cmms.Asset')),
                ('PurchaseRequestWO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedWO', to='cmms.WorkOrder')),
            ],
            options={
                'db_table': 'purchaserequest',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schChoices',
            field=models.IntegerField(choices=[(0, 'با تکرار زمان'), (1, 'بر اساس مقدار'), (2, 'رویداد محور')], default=0, null=True, verbose_name='اولویت'),
        ),
    ]
