# Generated by Django 3.2.6 on 2021-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_alter_partcategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='partcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partcategory',
            name='priority',
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
