# Generated by Django 3.2.6 on 2023-09-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_assetcadcoordination_z2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolidAmar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mogheiat', models.CharField(max_length=255)),
                ('keyfiat', models.CharField(max_length=255)),
                ('vaziat', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tolidamar',
            },
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('partName',)},
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AssetMeterTemplate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetMeterTemplateDesc', models.CharField(blank=True, max_length=50, null=True, verbose_name='شرح')),
                ('assetMeterTemplateMeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='کمیت اندازه گیری')),
            ],
            options={
                'db_table': 'Assetmetertemplate2',
                'ordering': ['assetMeterTemplateDesc'],
            },
        ),
    ]
