# Generated by Django 3.2.6 on 2024-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_assetcadcoordination_z2'),
    ]

    operations = [
        migrations.CreateModel(
            name='workorderSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismis_task_completoin_restriction', models.BooleanField(default=True, verbose_name='لغو چک کردن انجام کار')),
            ],
            options={
                'db_table': 'workordersetting',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='user_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Great'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor')], default=None, help_text='Rate the work order from Poor to Great', null=True),
        ),
        migrations.AlterField(
            model_name='assetcadfile',
            name='assetCadFile',
            field=models.FileField(max_length=200, upload_to='documents/%Y/%m/%d', verbose_name='فایل نقشه'),
        ),
    ]
