# Generated by Django 3.2.6 on 2022-01-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_remove_assetmetertemplate_assetmetertemplateasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGMTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BGMGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.batchmetergroup', verbose_name='گروه')),
                ('BGMTemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='قطعه')),
            ],
            options={
                'db_table': 'bgmtertemplate',
                'unique_together': {('BGMTemplate', 'BGMGroup')},
            },
        ),
    ]
