# Generated by Django 3.2.6 on 2021-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_remove_metercode_meterdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='metercode',
            name='meterDescription',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='َشرح'),
        ),
    ]
