# Generated by Django 3.2.6 on 2021-11-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_partcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='partCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.partcategory', verbose_name='دسته بندی'),
        ),
    ]
