# Generated by Django 3.2.6 on 2021-08-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_assetmeterreading_assetmetermeterreadingunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterLocation',
        ),
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterMeterReading',
        ),
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
        ),
        migrations.RemoveField(
            model_name='assetmeterreading',
            name='assetWorkorderMeterReading',
        ),
    ]
