# Generated by Django 2.0.2 on 2021-02-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_auto_20210131_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='completionNotes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='requiredCompletionTime',
            field=models.TimeField(blank=True, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='summaryofIssue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='خلاصه مشکل'),
        ),
    ]
