# Generated by Django 3.2.6 on 2023-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_assetcsvfile_partcsvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetTavali',
            field=models.IntegerField(default=0, verbose_name='شماره توالی'),
        ),
    ]
