# Generated by Django 3.2.6 on 2023-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_auto_20230911_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolidMoshakhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mogheiat', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('keyfiat', models.CharField(max_length=255, verbose_name='کیفیت')),
                ('vaziat', models.CharField(max_length=255, verbose_name='وضعیت')),
            ],
            options={
                'db_table': 'tolidmoshakhase',
            },
        ),
        migrations.DeleteModel(
            name='TolidAmar',
        ),
    ]
