# Generated by Django 2.0.2 on 2021-07-15 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_auto_20210715_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestDate2',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='مهلت تا تاریخ'),
        ),
    ]
