# Generated by Django 3.2.6 on 2022-01-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_bgmtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGMAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BGMAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
                ('BGMGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.batchmetergroup', verbose_name='گروه')),
            ],
            options={
                'db_table': 'bgmasset',
                'unique_together': {('BGMAsset', 'BGMGroup')},
            },
        ),
    ]
