# Generated by Django 3.2.6 on 2021-12-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_auto_20211130_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shMeterReadingMetrics',
        ),
    ]
