# Generated by Django 3.2.6 on 2022-01-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_auto_20220122_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestAssetMakan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedLocation', to='cmms.asset'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestAssetQty',
            field=models.FloatField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestDateFrom',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestDateTo',
            field=models.DateField(blank=True, null=True, verbose_name='مهلت تا تاریخ'),
        ),
    ]
