# Generated by Django 3.2.6 on 2024-02-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_auto_20240213_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpart',
            name='woPartStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='woStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'ارجاع به دفتر تاسیسات'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست'),
        ),
    ]
