# Generated by Django 3.2.6 on 2023-05-14 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_asset_assettavali'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingAmar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShiftTypes', models.IntegerField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], null=True, verbose_name='شیفت')),
                ('assetStartKilometer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کیلومتر شروع')),
                ('assetEndKilometer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کیلومتر پایان')),
                ('assetTotlaKilometer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کیلومتر تولید')),
                ('assetStartTime', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ساعت پایان شیفت قبل')),
                ('assetEndTime', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ساعت پایان شیفت جاری')),
                ('assetTotalTime', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ساعت تولید')),
                ('assetDarsad', models.FloatField(default=0, verbose_name='درصد')),
                ('assetDaf', models.IntegerField(default=0, verbose_name='داف')),
                ('operatorName', models.CharField(max_length=100, verbose_name='نام اپراتور')),
                ('assetAmarDate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assetName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ringAmar', to='cmms.asset', verbose_name='انبار')),
                ('userRegisterd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sysuser', verbose_name='کاربر ثبت کننده')),
            ],
        ),
    ]
