# Generated by Django 2.0.2 on 2021-07-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_purchaserequest_purchaserequestdate2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='PurchaseRequestDate2',
        ),
    ]
