# Generated by Django 3.2.6 on 2023-05-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_ringamar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ringamar',
            options={'ordering': ('assetAmarDate',)},
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ringAmar', to='cmms.asset', verbose_name='تجهیز'),
        ),
        migrations.AlterModelTable(
            name='ringamar',
            table='ringamar',
        ),
    ]
