# Generated by Django 3.2.6 on 2023-09-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_auto_20230911_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolidAmar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tedad', models.IntegerField()),
                ('meghdar', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.asset')),
                ('tolidmoshakhase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.tolidmoshakhase')),
            ],
            options={
                'db_table': 'TolidAmar',
            },
        ),
    ]
