# Generated by Django 3.2.6 on 2021-11-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_auto_20211129_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcategory',
            name='isPartOf',
        ),
    ]
