# Generated by Django 3.2.6 on 2024-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_auto_20240213_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderpart',
            name='woPartStatus',
            field=models.IntegerField(choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], default=1, verbose_name='وضعیت درخواست'),
        ),
    ]
