# Generated by Django 3.2.6 on 2021-12-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_remove_schedule_shmeterreadingmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shMeterReadingMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_shMeterReadingMetrics', to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
