# Generated by Django 3.2.6 on 2022-01-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_bgmasset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BGMTemplate',
            new_name='BMGTemplate',
        ),
    ]
