# Generated by Django 3.2.6 on 2022-04-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_auto_20220122_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('taskDescription',)},
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestAsset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedAsset', to='cmms.asset', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestRequestedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestdUser', to='cmms.sysuser', verbose_name='کاربر درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='adminNote',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات مدیر'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completionNotes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workInstructions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دستورالعمل'),
        ),
    ]
