# Generated by Django 2.0.2 on 2021-07-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_remove_purchaserequest_purchaserequestdate2'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestAuthUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestAuthUser', to='cmms.SysUser', verbose_name='کاربر مجاز'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestRequestedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestdUser', to='cmms.SysUser', verbose_name='کاربر درخواست کننده'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestAssetQty',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='تعداد'),
        ),
    ]
