# Generated by Django 3.2.6 on 2024-02-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_alter_workorderpart_wopartstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderpart',
            name='woPartStatus',
        ),
    ]
