# Generated by Django 3.2.6 on 2023-09-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_tolidamar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolidamar',
            name='tolidmoshakhase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.tolidmoshakhase'),
        ),
    ]
