# Generated by Django 3.2.6 on 2022-05-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_auto_20220425_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmgtemplate',
            options={'ordering': ['BMGTemplate']},
        ),
    ]
