# Generated by Django 3.2.6 on 2021-11-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_remove_partcategory_ispartof'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='isPartOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.partcategory', verbose_name='زیر مجموعه'),
        ),
    ]
