# Generated by Django 3.2.6 on 2023-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_auto_20230515_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ringamar',
            options={'ordering': ('-assetAmarDate',)},
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='ShiftTypes',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True, verbose_name='شیفت'),
        ),
    ]
