# Generated by Django 3.2.6 on 2022-01-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_rename_bgmtemplate_bmgtemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BGMAsset',
            new_name='BMGAsset',
        ),
        migrations.RenameField(
            model_name='bmgasset',
            old_name='BGMAsset',
            new_name='BMGAsset',
        ),
        migrations.RenameField(
            model_name='bmgasset',
            old_name='BGMGroup',
            new_name='BMGGroup',
        ),
        migrations.RenameField(
            model_name='bmgtemplate',
            old_name='BGMGroup',
            new_name='BMGGroup',
        ),
        migrations.RenameField(
            model_name='bmgtemplate',
            old_name='BGMTemplate',
            new_name='BMGTemplate',
        ),
        migrations.AlterUniqueTogether(
            name='bmgasset',
            unique_together={('BMGAsset', 'BMGGroup')},
        ),
        migrations.AlterUniqueTogether(
            name='bmgtemplate',
            unique_together={('BMGTemplate', 'BMGGroup')},
        ),
    ]
