# Generated by Django 3.2.6 on 2021-12-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_schedule_shmeterreadingmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shMeterReadingWhenMetric',
        ),
    ]
