# Generated by Django 3.2.6 on 2022-01-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_auto_20220112_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtemplate',
            name='BMGTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='مترینگ'),
        ),
    ]
