# Generated by Django 2.0.2 on 2021-07-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_auto_20210717_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='PurchaseRequestStatus',
            new_name='PurchaseRequestStatus2',
        ),
    ]
