# Generated by Django 3.2.6 on 2021-11-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_partcategory_ispartof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiexception',
            name='stopcode',
        ),
    ]
