# Generated by Django 3.2.6 on 2023-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_auto_20230515_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetTavali',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره توالی'),
        ),
    ]
