# Generated by Django 3.2.6 on 2021-12-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_remove_schedule_shmeterreadingwhenmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shMeterReadingWhenMetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_meter_when', to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
