# Generated by Django 3.2.6 on 2024-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_remove_workorderpart_wopartstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpart',
            name='woPartWaitingforFulfill',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='در انتظار تامین'),
        ),
    ]
