# Generated by Django 3.2.6 on 2022-01-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_schedule_shmeterreadingwhenmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schTriggerTime',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان راه اندازی'),
        ),
    ]
