# Generated by Django 3.2.6 on 2023-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_auto_20230917_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolidmoshakhase',
            name='mogheiat',
            field=models.CharField(max_length=255, unique=True, verbose_name='موقعیت'),
        ),
    ]
