# Generated by Django 3.2.6 on 2024-02-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_workorderpart_wopartwaitingforfulfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderpart',
            options={'permissions': (('can_fulfill', 'Can Fulfill'),)},
        ),
    ]
