# Generated by Django 3.2.6 on 2021-11-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_remove_kpiexception_stopcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiexception',
            name='stopcode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cmms.stopcode', unique=True, verbose_name='کد توقف'),
            preserve_default=False,
        ),
    ]
