# Generated by Django 3.2.6 on 2022-01-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_alter_bmgtemplate_bmgtemplate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bmgtemplate',
            table='bmgtemplate',
        ),
    ]
