# Generated by Django 3.2.6 on 2022-01-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_alter_bmgtemplate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bmgasset',
            table='bmgasset',
        ),
    ]
