# Generated by Django 3.2.6 on 2021-08-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_remove_assetmeterreading_assetmetermeterreadingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
