# Generated by Django 3.2.6 on 2023-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_alter_ringamar_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringamar',
            name='assetEndKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='کیلومتر پایان'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetEndTime',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ساعت پایان شیفت جاری'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetStartKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='کیلومتر شروع'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetStartTime',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ساعت پایان شیفت قبل'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetTotalTime',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ساعت تولید'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetTotlaKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='کیلومتر تولید'),
        ),
    ]
