# Generated by Django 3.2.6 on 2021-11-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_kpiexception_stopcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlife',
            name='assetCauseCode',
        ),
    ]
