# Generated by Django 3.2.6 on 2025-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_alter_workorderpart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('reportName',)},
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='manager_confirmed',
            field=models.BooleanField(default=False, verbose_name='Manager Confirmation'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='manager_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manager Confirmation Time'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='staff_confirmed',
            field=models.BooleanField(default=False, verbose_name='Staff Confirmation'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='staff_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Staff Confirmation Time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='woStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'ارجاع به دفتر تاسیسات'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه'), (10, 'تامین شده نسبی'), (11, 'تامین شده')], null=True, verbose_name='وضعیت درخواست'),
        ),
    ]
