# Generated by Django 3.2.6 on 2022-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_schedule_schtriggertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schTriggerTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='زمان راه اندازی'),
        ),
    ]
