# Generated by Django 3.2.6 on 2023-11-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_alter_tolidmoshakhase_mogheiat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseStatus', models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست')),
                ('PurchaseDateTo', models.DateField(auto_now_add=True, verbose_name='تاریخ ')),
                ('PurchaseCompletionDate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('PurchaseRequestedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestdUserMain', to='cmms.sysuser', verbose_name='کاربر درخواست کننده')),
                ('PurchaseTayeedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseAdmitterMain', to='cmms.sysuser', verbose_name='کاربر تایید کننده')),
            ],
            options={
                'db_table': 'mainpurchase',
            },
        ),
        migrations.CreateModel(
            name='RequestVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgFile', models.FileField(max_length=200, upload_to='documents/%Y/%m/%d')),
                ('msgFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('msgFileworkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.mainpurchase')),
            ],
            options={
                'db_table': 'requestvoice',
            },
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgFile', models.FileField(max_length=200, upload_to='documents/%Y/%m/%d')),
                ('msgFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('msgFileworkorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.mainpurchase')),
            ],
            options={
                'db_table': 'purchasefile',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseRequestStatus', models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست')),
                ('PurchaseRequestCompletionDate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('PurchaseRequestMoreInfo', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات بیشتر')),
                ('PurchaseRequestAssetNotInInventory', models.CharField(blank=True, max_length=100, null=True, verbose_name='ناموجود در انبار؟ اطلاعات بیشتری شرح دهید')),
                ('PurchaseRequestQty', models.FloatField(verbose_name='تعداد')),
                ('PurchaseRequestQtyNot', models.FloatField(blank=True, null=True, verbose_name='کمیت')),
                ('PurchaseRequestNot', models.BooleanField(default=False, verbose_name='در صورت عدم تهیه تولید دچار وقفه میشود')),
                ('PurchaseRequestNotInList', models.BooleanField(default=False, null=True)),
                ('PurchaseRequestDateTo', models.DateField(auto_now_add=True, verbose_name='مهلت تا تاریخ')),
                ('settingTimestamp', models.DateTimeField(auto_now_add=True)),
                ('PurchaseRequestAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedAsset3', to='cmms.asset', verbose_name='تجهیز')),
                ('PurchaseRequestAssetMakan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImpactedLocation3', to='cmms.asset')),
                ('PurchaseRequestAuthUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestAuthUser3', to='cmms.sysuser', verbose_name='کاربر مجاز')),
                ('PurchaseRequestPartName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestedPart3', to='cmms.part', verbose_name='مشخصات قطعه')),
                ('PurchaseRequestPurchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainpurchase3', to='cmms.mainpurchase')),
                ('PurchaseRequestRequestedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestdUser3', to='cmms.sysuser', verbose_name='کاربر درخواست کننده')),
                ('PurchaseRequestTayeedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseAdmitter3', to='cmms.sysuser', verbose_name='کاربر تایید کننده')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers3', to='cmms.business')),
            ],
            options={
                'db_table': 'purchaserequests',
                'ordering': ('-id',),
                'permissions': [('change_request_status', 'Can change the status of purchase request status')],
            },
        ),
    ]
