# Generated by Django 2.0.2 on 2021-07-18 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_auto_20210717_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='PurchaseRequestDate',
            new_name='PurchaseRequestDateTo',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestAssetNot',
            field=models.BooleanField(default=False, verbose_name='در صورت عدم تهیه تولید دچار وقفه میشود'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='PurchaseRequestDateFrom',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestAssetQty',
            field=models.FloatField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestAssetQtyNot',
            field=models.FloatField(blank=True, null=True, verbose_name='کمیت'),
        ),
    ]
