# Generated by Django 2.0.2 on 2021-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0012_auto_20210718_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomgroup',
            name='BOMGroupName',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام گروه BOM'),
        ),
    ]
