# Generated by Django 3.2.6 on 2023-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0012_auto_20230520_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ringamar',
            options={'ordering': ('-assetAmarDate', '-id')},
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetEndKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='کیلومتر پایان'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetStartKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='کیلومتر شروع'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetTotlaKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='کیلومتر تولید'),
        ),
    ]
