# Generated by Django 3.2.6 on 2022-01-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0012_alter_bmgasset_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmeterreading',
            name='assetMeterMeterReadingUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
    ]
