# Generated by Django 3.2.6 on 2025-01-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0012_auto_20250125_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderpart',
            options={'permissions': (('can_fulfill', 'Can Fulfill'), ('can_manager_fulfill', 'Manager Can Fulfill'), ('can_stuff_fulfill', 'Stuff Can Fulfill'))},
        ),
    ]
