# Generated by Django 3.2.6 on 2021-11-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0012_remove_assetlife_assetcausecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlife',
            name='assetCauseCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetlifeCauseCode', to='cmms.causecode', verbose_name='کد علت'),
        ),
    ]
