# Generated by Django 3.2.6 on 2024-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0012_mainpurchase_purchaserequests_requestfile_requestvoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsetting',
            options={'permissions': (('view_dashboard', 'view dashboard'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol'))},
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='registerd_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مصرف'),
        ),
    ]
