# Generated by Django 3.2.6 on 2022-01-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_alter_assetmeterreading_assetmetermeterreadingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmeterreading',
            name='assetMeterMeterReading',
            field=models.FloatField(default=0.0, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shMeterReadingMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_shMeterReadingMetrics', to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shMeterReadingWhenMetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_meter_when', to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
    ]
