# Generated by Django 2.0.2 on 2021-07-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_auto_20210724_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterCode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد')),
                ('meterDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='َرح')),
            ],
            options={
                'db_table': 'metercode',
            },
        ),
    ]
