# Generated by Django 3.2.6 on 2022-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_assetpart_assetpartdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schCreateOnStartDate',
            field=models.BooleanField(default=False, verbose_name='مقدار پایانی'),
        ),
    ]
