# Generated by Django 3.2.6 on 2021-08-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_metercode_meterabbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shMeterReadingMetrics',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shMeterReadingWhenMetric',
        ),
    ]
