# Generated by Django 3.2.6 on 2022-11-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_alter_purchaserequest_purchaserequestdatefrom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('assetName',)},
        ),
        migrations.CreateModel(
            name='AssetException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetExceptionAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='کد پرت')),
            ],
            options={
                'db_table': 'assetexception',
            },
        ),
    ]
