# Generated by Django 3.2.6 on 2023-05-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_auto_20230521_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringamar',
            name='assetEndKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='کیلومتر پایان شیفت جاری'),
        ),
        migrations.AlterField(
            model_name='ringamar',
            name='assetStartKilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='کیلومتر پایان شیفت قبل'),
        ),
    ]
