# Generated by Django 3.2.6 on 2021-08-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_auto_20210814_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shMeterReadingMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_shMeterReadingMetrics', to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shMeterReadingWhenMetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_meter_when', to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
