# Generated by Django 3.2.6 on 2022-01-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_schedule_schcreateonstartdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='taskTemplateMetrics',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schCreateOnStartDate',
            field=models.BooleanField(default=False, verbose_name='ساختن در زمان شروع'),
        ),
    ]
