# Generated by Django 3.2.6 on 2023-04-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_auto_20221113_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCadCoordination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('assetCoord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='دارایی')),
            ],
            options={
                'db_table': 'assetcadcoordination',
            },
        ),
    ]
