# Generated by Django 2.0.2 on 2021-07-31 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_metercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.MeterCode', verbose_name='واحد اندازه گیری'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='workOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompleteUserTask', to='cmms.WorkOrder'),
        ),
    ]
