# Generated by Django 3.2.6 on 2022-01-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_auto_20220114_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='taskTemplateMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
    ]
