# Generated by Django 3.2.6 on 2025-07-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
