# Generated by Django 3.2.6 on 2023-04-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0015_assetcadcoordination'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetCadFile', models.FileField(max_length=200, upload_to='documents/')),
                ('assetCadFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('assetCadFileAssetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.asset')),
            ],
        ),
    ]
