# Generated by Django 3.2.6 on 2023-03-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0015_usershif'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserShif',
            new_name='UserShift',
        ),
        migrations.AddField(
            model_name='sysuser',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.usershift'),
        ),
    ]
