# Generated by Django 3.2.6 on 2022-01-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0016_alter_tasks_taskmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
    ]
