# Generated by Django 3.2.6 on 2023-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0016_auto_20230326_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='end_time',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='usershift',
            name='start_time',
            field=models.TimeField(verbose_name='زمان شروع'),
        ),
    ]
