# Generated by Django 3.2.6 on 2023-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0017_auto_20230326_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم شیفت'),
        ),
    ]
