# Generated by Django 3.2.6 on 2023-04-17 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0017_alter_assetcadfile_assetcadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcadfile',
            name='assetCadFileAssetId',
            field=models.ForeignKey(default=datetime.datetime(2023, 4, 17, 18, 52, 31, 729644), on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='assetcadfile',
            table='assetcadfile',
        ),
    ]
