# Generated by Django 3.2.6 on 2022-01-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0017_remove_tasktemplate_tasktemplatemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='taskTemplateMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
