# Generated by Django 3.2.6 on 2021-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0019_metercode_meterabbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='assetFile',
            field=models.FileField(max_length=200, upload_to='documents/'),
        ),
    ]
