# Generated by Django 3.2.6 on 2021-08-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0020_alter_assetfile_assetfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misccost',
            name='miscCoastType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscCoastWorkorder', to='cmms.misccostcode', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='workorderfile',
            name='woFile',
            field=models.FileField(max_length=200, upload_to='documents/'),
        ),
    ]
