# Generated by Django 3.2.6 on 2022-01-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0020_auto_20220115_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='واحد اندازه گیری'),
        ),
    ]
