# Generated by Django 3.2.6 on 2022-01-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0020_kpiexception_stopcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMeterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetMeterTemplateDesc', models.CharField(blank=True, max_length=50, null=True, verbose_name='شرح')),
                ('assetMeterTemplateAsset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.asset', verbose_name='نام دارایی')),
                ('assetMeterTemplateMeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.metercode', verbose_name='کمیت اندازه گیری')),
            ],
            options={
                'db_table': 'Assetmetertemplate',
            },
        ),
    ]
