# Generated by Django 3.2.6 on 2022-01-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0021_alter_tasks_taskmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shMeterReadingMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_shMeterReadingMetrics', to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shMeterReadingWhenMetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_meter_when', to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskMetrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.assetmetertemplate', verbose_name='واحد اندازه گیری'),
        ),
    ]
