# Generated by Django 3.2.6 on 2021-08-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0021_auto_20210817_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misccost',
            name='miscCoastIndividual',
        ),
    ]
