# Generated by Django 3.2.6 on 2021-08-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0022_remove_misccost_misccoastindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='misccost',
            name='miscCoastIndividual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscCoastIndividuals', to='cmms.business', verbose_name='پیمانکار'),
        ),
    ]
