# Generated by Django 3.2.6 on 2021-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0023_misccost_misccoastindividual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='timecreated',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان ایجاد'),
        ),
    ]
