# Generated by Django 3.2.6 on 2021-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0024_alter_workorder_timecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
