from .dashboardview import *
from cmms.views.maintenanceview import *
from cmms.views.miniworkorderview import *
from cmms.views.sworkorderview import *
from cmms.views.taskView import *
from cmms.views.wopartview import *
from cmms.views.wometerview import *
from cmms.views.wopertview import *
from cmms.views.womiscview import *
from cmms.views.wonotifyview import *
from cmms.views.bomgroupview import *
from cmms.views.bmg_templateview import *
from cmms.views.bmgassetview import *
from cmms.views.batchmetergroupview import *
from cmms.views.wofileview import *
from cmms.views.scheduleview import *
from cmms.views.AssetView import *
from cmms.views.assetpartview    import *
from cmms.views.assetmeterview    import *
from cmms.views.asseteventview    import *
from cmms.views.assetmetertemplateview    import *
from cmms.views.assetuserview    import *
from cmms.views.assetfileview import *
from cmms.views.assetlifeview import *
from cmms.views.assetwarantyview import *
from cmms.views.assetbusinessview import *
from cmms.views.assetpurchaseview import *
from cmms.views.partview import *
from cmms.views.partlocationview import *
from cmms.views.partstockview import *
from cmms.views.partuserview import *
from cmms.views.partwarantyview import *
from cmms.views.partbusinessview import *
from cmms.views.partpurchaseview import *
from cmms.views.partfileview import *
from cmms.views.stockview import *
from cmms.views.businessview import *
from cmms.views.businessfileview import *
from cmms.views.businessassetview import *
from cmms.views.businesspartview import *
from cmms.views.mailview import *
from cmms.views.projectview import *
from cmms.views.projectScheduledview import *
from cmms.views.projectwoview import *
from cmms.views.projectuserview import *
from cmms.views.projectfileview import *
from cmms.views.assetcadview import *
from cmms.views.assetcadfileview import *



from cmms.views.eventview import *
from cmms.views.maintenancetypeview import *
from cmms.views.attendanceview import *
from cmms.views.assetcategoryview import *
from cmms.views.partcategoryview import *
from cmms.views.machinecategoryview import *
from cmms.views.userview import *
from cmms.views.usergroupsview import *
from cmms.views.userfileview import *
from cmms.views.usercertificationview import *
from cmms.views.userlogview import *
from cmms.views.adsetview import *
from cmms.views.reportview import *
from cmms.views.workorderProblemview import *
from cmms.views.MeterCodeview import *
from cmms.views.assetExceptionview import *
from cmms.views.misccostcodeview import *
from cmms.views.workorderStopview import *
from cmms.views.workorderPertview import *
from cmms.views.eqcostsettingview import *
from cmms.views.workorderActionview import *
from cmms.views.workorderCauseview import *
from cmms.views.offlinestatusview import *
from cmms.views.kpiexceptionview import *
from cmms.views.settingview import *
from cmms.views.simplereportview import *
from cmms.views.calendar import *
from cmms.views.userprofile import *
from cmms.views.userGroupview import *
from cmms.views.taskgroupview import *
from cmms.views.tasktemplateview import *
from cmms.views.taskgroupassetcategoryview import *
from cmms.views.taskgroupfileview import *
from cmms.views.wolog import *
from cmms.views.adsetview import *
from cmms.views.bomgrouppartview import *
from cmms.views.bomgroupassetview import *
from cmms.views.dash_assetview import *
from cmms.views.purchaseboardview import *
from cmms.views.purchaserequestview import *
from cmms.views.token import *
from cmms.views.ringamarview import *
from cmms.views.tolidamarview import *
from cmms.views.login import *
